apiVersion: v1
kind: Namespace
metadata:
  name: backend
  labels:
    project: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: backend
  name: apache-backend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: backend
    spec:
      containers:
      - name: my-apache
        image: centos/httpd:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: backend
  labels:
    name: backend
spec:
  type: NodePort
  clusterIP: None
  ports:
    - port: 80
      nodePort: 30066

  selector:
    name: backend
