apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels:
    project: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: frontend
  name: apache-frontend
spec:
  replicas: 5
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - name: my-apache
        image: centos/httpd:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: frontend
  labels:
    name: frontend
spec:
  type: NodePort
  clusterIP: None
  ports:
    - port: 80
      nodePort: 30067

  selector:
    name: frontend
