apiVersion: v1
kind: Service
metadata:
  name: nginxlb
  labels:
    name: nginxlb
spec:
  type: NodePort
  ports:
    - name: http-alt
      port: 8080
      nodePort: 30000
    - name: http
      port: 80
      nodePort: 30001
  selector:
    app: nginxplus
